### ISSUE TITLE
Add eslint and prettier

### ISSUE THREAD

**Issue by jgcmarins** [Bastiani/social-condominium#5]
- https://github.com/eslint/eslint
- https://github.com/prettier/prettier
- https://github.com/entria/graphql-dataloader-boilerplate/blob/master/.eslintrc
- https://github.com/entria/graphql-dataloader-boilerplate/blob/master/package.json#L32
- https://github.com/entria/graphql-dataloader-boilerplate/blob/master/package.json#L73

**Comment by Bastiani** [comment]
already add this, i not work without these plugins
![image](https://user-images.githubusercontent.com/9096756/33659591-db8a8e94-da67-11e7-9053-d066a23485b4.png)

**Comment by Bastiani** [comment]
I start the project with more than 40 errors in boilerplate...
And github hooks for pre push not work then i ignore this hook
https://github.com/Bastiani/social-condominium/pull/1

**Comment by jgcmarins** [comment]
great!
If you think you can improve it with [lint-staged](https://github.com/okonet/lint-staged), just do it \o/
But if it's already done, we can close this issues :)

**Comment by Bastiani** [comment]
Thx!
